const questions = [
    "What is your favorite color?",
    "Do you have any pets?",
    "What is your dream job?",
    "If you could travel anywhere in the world, where would you go?",
    "What is your favorite book?",
    "What is your go-to hobby?",
    "If you could meet any historical figure, who would it be?",
    "What is your favorite type of music?",
    "What is your favorite movie?",
    "If you could have dinner with any fictional character, who would it be?",
    "What is your favorite food?",
    "What is your most memorable vacation?",
    "If you could have any superpower, what would it be?",
    "What is your favorite season?",
    "Do you prefer coffee or tea?",
    "What is your favorite outdoor activity?",
    "If you could time travel, where would you go?",
    "What is your favorite childhood memory?",
    "What is your dream car?",
    "If you could learn any new skill, what would it be?",
    "What is your favorite TV show?",
    "If you could have any animal as a pet, what would it be?",
    "What is your favorite holiday?",
    "If you could have dinner with any celebrity, who would it be?",
    "What is your favorite way to relax?",
    "Do you prefer sweet or savory foods?",
    "What is your favorite type of exercise?",
    "If you could live in any fictional world, where would it be?",
    "What is your favorite type of dessert?",
    "If you could change one thing about the world, what would it be?",
    "What is your biggest accomplishment?",
    "If you could have any job for a day, what would it be?",
    "What is your favorite board game?",
    "If you could eliminate one thing from your daily routine, what would it be?",
    "What is your favorite childhood game?",
    "If you could have any technology gadget, what would it be?",
    "What is your favorite way to spend a lazy Sunday?",
    "If you could be any fictional character for a day, who would it be?",
    "What is your favorite type of art?",
    "If you could have any talent, what would it be?",
    "What is your favorite way to stay active?",
    "If you could learn any language, what would it be?",
    "What is your favorite childhood TV show?",
    "If you could have any job in the world, what would it be?",
    "What is your favorite childhood book?",
    "If you could visit any country, where would you go?",
    "What is your favorite way to start the day?",
    "If you could have any car, what would it be?",
    "What is your favorite type of cuisine?",
    "If you could have any job in the world, what would it be?",
    "What is your favorite memory from school?",
    "If you could have any animal as a mythical pet, what would it be?",
    "What is your favorite way to celebrate a special occasion?",
    "If you could have any job for a day, what would it be?",
    "What is your favorite way to spend time with family?",
    "If you could have any talent, what would it be?",
    "What is your favorite childhood toy?",
    "If you could have any job in the world, what would it be?",
    "What is your favorite type of movie?",
    "If you could have dinner with any historical figure, who would it be?",
    "What is your dream job?",
    "What is your favorite book?",
    "If you could travel anywhere in the world, where would you go?",
    "What is your favorite type of music?",
    "What is your favorite movie?",
    "If you could have dinner with any fictional character, who would it be?",
    "What is your favorite food?",
    "What is your most memorable vacation?",
    "If you could have any superpower, what would it be?",
    "What is your favorite season?",
    "Do you prefer coffee or tea?",
    "What is your favorite outdoor activity?",
    "If you could time travel, where would you go?",
    "What is your favorite childhood memory?",
    "What is your dream car?",
    "If you could learn any new skill, what would it be?",
    "What is your favorite TV show?",
    "If you could have any animal as a pet, what would it be?",
    "What is your favorite holiday?",
    "If you could have dinner with any celebrity, who would it be?",
    "What is your favorite way to relax?",
    "Do you prefer sweet or savory foods?",
    "What is your favorite type of exercise?",
    "If you could live in any fictional world, where would it be?",
    "What is your favorite type of dessert?",
    "If you could change one thing about the world, what would it be?",
    "What is your biggest accomplishment?",
    "If you could have any job for a day, what would it be?",
    "What is your favorite board game?",
    "If you could eliminate one thing from your daily routine, what would it be?",
    "What is your favorite childhood game?",
    "If you could have any technology gadget, what would it be?",
    "What is your favorite way to spend a lazy Sunday?",
    "If you could be any fictional character for a day, who would it be?",
    "What is your favorite type of art?",
    "If you could have any talent, what would it be?",
    "What is your favorite way to stay active?",
    "If you could learn any language, what would it be?",
    "What is your favorite childhood TV show?",
    "If you could have any job in the world, what would it be?",
    "What is your favorite childhood book?",
    "If you could visit any country, where would you go?",
    "What is your favorite way to start the day?",
    "If you could have any car, what would it be?",
    "What is your favorite type of cuisine?",
    "If you could have any job in the world, what would it be?",
    "What is your favorite memory from school?",
    "If you could have any animal as a mythical pet, what would it be?",
    "What is your favorite way to celebrate a special occasion?"
];


function generateRandomQuestion() {
    const randomIndex = Math.floor(Math.random() * questions.length);
    const randomQuestion = questions[randomIndex];
    document.getElementById('randomQuestion').innerText = randomQuestion;
}
